### ISSUE TITLE
Just a quick thanks

### ISSUE THREAD

**Issue by ghost** [gldrenthe89/nova-calculated-field#1]
Just wanted to say thank you for your work on this. It is quite helpful. No issues or problems, seems to work perfectly.

**Comment by gldrenthe89** [comment]
Hi @mbrown3116, your comment is really appreciated.  thanks man. 
To be completely honest, there is currently an issue in not being able to edit the calculated listener number field. This is something i haven't had the time to take a big look in.
I first need to create broadcast and listener Date / Time fields. Hope to get that done soon.

**Comment by kevariable** [comment]
Big thanks for this package !
