### ISSUE TITLE
Laravel Nova 4

### ISSUE THREAD

**Issue by yastrebf** [gldrenthe89/nova-calculated-field#12]
Hi! What about Laravel Nova 4?

gldrenthe89/nova-calculated-field[V2.4, ..., v2.4.1] require laravel/nova ~3.0 -> found laravel/nova[dev-master, v3.0.0, ..., 3.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (~4.0)

**Comment by gldrenthe89** [comment]
You can achieve almost the same with the new ->dependsOn() function most fields have in Nova 4.0, see: [https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields](https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields)
