### ISSUE TITLE
Multiple listener fields

### ISSUE THREAD

**Issue by blackfyre** [gldrenthe89/nova-calculated-field#5]
Is there a way to add multiple listener fields?
Currently only 1 listener seems to be working on each channel...

update: having the broadcaster field broadcast to multiple channel doesn't seem to solve the problem

**Comment by gldrenthe89** [comment]
Sorry no time to look in to currently. Cant remember te exact mechanics.

**Comment by Saifallak** [comment]
haveing the same issue, any ideas?

**Comment by blackfyre** [comment]
I've forked the repo and started working on the fix...

**Comment by Saifallak** [comment]
Looking forward for it, please notify me ASAP that fix is done, i would appreciate it

**Comment by gldrenthe89** [comment]
should be fixed by:Saifallak in: https://github.com/gldrenthe89/nova-calculated-field/pull/8

**Comment by Saifallak** [comment]
Nope, it doesn't,,..
This should be reopened..
I hope someone fixes this

**Comment by gldrenthe89** [comment]
Reopend

**Comment by blackfyre** [comment]
Soo... After a little bit of investigation, it seems that the problem is with VueJS and how Nova handles it.
VueJS tends to re-use the same component, which is fine for conserving memory and so on, but in our case, if the listener fields are of the same type, the same debounced update gets called every time. If there are multiple listener field types, it'll work just fine.

It's easy to fix, once you know the problem...
In the `created` hook, I've added the content of the `calculateValue` dynamically to the `data` object with an unique key, and called that key dynamically when required.

Due to the extensive modifications on the code base, I cannot share my fork atm... it's still a work in progress, however, here's the mixin created to do this 😄 

```javascript
import _ from "lodash";

export default {
    data() {
        return {
            updater: {}
        }
    },
    created() {
        Nova.$on(this.field.listensTo, this.messageReceived)

        this.$set(this.updater, this.field.attribute, _.debounce((force = false) => {
            this.calculating = true;

            Nova.request().post(
                `/zenosyne/calculatron/calculatron/${this.resourceName}/${this.field.attribute}`,
                this.field_values
            ).then((response) => {
                if (
                    !(response.data.disabled && this.field.isUpdating)
                    ||
                    force
                ) {
                    this.value = response.data.value
                }
                this.calculating = false;
            }).catch(() => {
                this.calculating = false;
            });
        }, 300));
    },
    methods: {
        messageReceived(message) {
            this.field_values[message.field_name] = message.value;
            this.calculateValue()
        },
        calculateValue(force = false) {
            this.updater[this.field.attribute](force);
        }
    }
};
```

**Comment by Saifallak** [comment]
looking forward for your fork/solution @blackfyre
