### ISSUE TITLE
Does not work with existing DB values

### ISSUE THREAD

**Issue by alexander-code** [gldrenthe89/nova-calculated-field#6]
Hi, as the original component it does not work with existing db values. If you edit a record and then 
type something in any broadcaster, it doesn't taking into account the values of the other broadcaster.

Any chance that you can fix this issue.

Thanks in advance.

**Comment by gldrenthe89** [comment]
You are free to create a PR. Currently no time to play with this package. Sorry.

**Comment by alexander-code** [comment]
No time either, sorry, thanks for the reply.

**Comment by Saifallak** [comment]
> No time either, sorry, thanks for the reply.

any chance of solution or alternative
