### ISSUE TITLE
Doesn't work on actions 

### ISSUE THREAD

**Issue by dmason30** [gldrenthe89/nova-calculated-field#9]
If you stick the example from the readme into a nova action it is unable to find the fields for calculation and it throws the following exception:

```json
{
    "message": "Unable to find the field required to calculate this value",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
}
```

**Comment by gldrenthe89** [comment]
HI,
Feel free to create a PR with the correct readme information

**Comment by dmason30** [comment]
@gldrenthe89 The readme example isn't the issue. The actual package itself doesn't correctly detect its being used within an action and only checks fields on the resource rather than the action.

**Comment by gldrenthe89** [comment]
The package isn't made to be used in a action. Purely for use on create and edit forms.

Feel free to create a PR so i can be used in a action.
